VoD.Website/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoD.Core;
using VoD.DAL.Services.Interfaces;
using VoD.Website.Models;


namespace VoD.Website.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IGenreRepository repository;

        public CategoryController(IGenreRepository repository)
        {
            this.repository = repository;
        }

        //
        // GET: /Category/
        public ActionResult Index()
        {
            var genresList = repository.GetAllGenresWithMovieCount();
            return View(genresList);
        }

        public ActionResult ViewCategory(int categoryId)
        {
            var moviesFromCategory = repository.GetMoviesFromCategory(categoryId);
            return View(moviesFromCategory);
        }
	}
}

VoD.Website/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoD.DAL.DataContexts;
using VoD.Core;

// for GetUserId
using Microsoft.AspNet.Identity;
using VoD.DAL.Services.Interfaces;

namespace VoD.Website.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepository repository;

        public MovieController(IMovieRepository repository)
        {
            this.repository = repository;
        }

        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Description(int movieId)
        {
            var description = repository.GetMovieViewModelDetails(movieId);
            return View(description);
        }

        public ActionResult Search(string title)
        {
            var foundMovies = repository.SearchMovies(title);
            if (foundMovies.Count == 0)
            {
                return View("SearchNotFound");
            }

            return View(foundMovies);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Comment(int movieId)
        {
            var movie = repository.GetById(movieId);
            return View(movie);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Comment(Comment movieComment)
        {
            if (ModelState.IsValid)
            {
                var userGuid = User.Identity.GetUserId();
                movieComment.AuthorGuid = Guid.Parse(userGuid);
                repository.AddCommentToMovie(movieComment);
            }

            return RedirectToAction("Description", new { movieId = movieComment.MovieId });
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveComment(int commentId, int movieId)
        {
            repository.RemoveCommentFromMovie(commentId, movieId);
            return RedirectToAction("Description", new { movieId = movieId });
        }
	}
}

VoD.Website/Views/Category/Index.cshtml
@model IEnumerable<VoD.Website.Models.CategoryViewModel>

@{
    ViewBag.Title = "Kategorie";
}

<h2>Kategorie</h2>

<table class="table">
    <tr>
        <th>
            Gatunek
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name) (@item.Count)
        </td>
        <td>
            @Html.ActionLink("Pokaż wszystkie", "ViewCategory", "Category", new { categoryId = item.Id }, null)
        </td>
    </tr>
}

</table>

VoD.Website/Views/Category/ViewCategory.cshtml
@model IEnumerable<VoD.Website.Models.MoviesFromCategoryViewModel>

@{
    ViewBag.Title = "Filmy z wybranej kategorii";
}

<h2>Filmy z wybranej kategorii</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Year)
        </td>
        <td>
            @Html.ActionLink("Więcej", "Description", "Movie", new { movieId=item.Id }, null)
        </td>
    </tr>
}

</table>