VoD.Website/Controllers/ManageActorsController.cs
using System;
using System.Collections.Generic;

using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoD.Core;
using VoD.DAL.Services.Interfaces;

namespace VoD.Website.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ManageActorsController : Controller
    {
        private readonly IActorRepository repository;

        public ManageActorsController(IActorRepository repository)
        {
            this.repository = repository;
        }

        //
        // GET: /ManageActors/
        public ActionResult Index()
        {
            var actorsList = repository.GetAll();
            return View(actorsList);
        }

        [HttpGet]
        public ActionResult AddActor()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddActor(Actor actor)
        {
            if (ModelState.IsValid)
            {
                repository.Add(actor);
                return RedirectToAction("Index");
            }

            return View(actor);
        }

        [HttpGet]
        public ActionResult EditActor(int actorId)
        {
            var actor = repository.GetById(actorId);
            return View(actor);
        }

        [HttpPost]
        public ActionResult EditActor(Actor actor)
        {
            if (ModelState.IsValid)
            {
                repository.Update(actor);
                return RedirectToAction("Index");
            }

            return RedirectToAction("EditActor", new { actorId = actor.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveActor(int actorId)
        {
            repository.RemoveById(actorId);
            return RedirectToAction("Index");
        }
	}
}

VoD.Website/Views/ManageActors/AddActor.cshtml
@model VoD.Core.Actor

@{
    ViewBag.Title = "Dodaj aktora";
}

<h2>Dodaj aktora</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Aktor</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

VoD.Website/Views/ManageActors/EditActor.cshtml
@model VoD.Core.Actor

@{
    ViewBag.Title = "Edytuj aktora";
}

<h2>Edytuj aktora</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Aktor</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

VoD.Website/Views/ManageActors/Index.cshtml
@model IEnumerable<VoD.Core.Actor>

@{
    ViewBag.Title = "Aktorzy";
}

<h2>Aktorzy</h2>

<p>
    @Html.ActionLink("Dodaj nowego", "AddActor")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "EditActor", new { actorId=item.Id }) |
            @using (@Html.BeginForm("RemoveActor", "ManageActors", FormMethod.Post, new { @style = "display:inline;" }))
            {
                @Html.AntiForgeryToken()
                <input name="actorId" value="@item.Id" hidden />
                <a class="removePosition">Usuń</a>
            }
        </td>
    </tr>
}

</table>

@section scripts {
    <script src="~/Scripts/helpers.js"></script>
}