VoD.Website/Controllers/ManageDirectorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoD.Core;
using VoD.DAL.Services.Interfaces;

namespace VoD.Website.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ManageDirectorsController : Controller
    {
        private readonly IDirectorRepository repository;

        public ManageDirectorsController(IDirectorRepository repository)
        {
            this.repository = repository;
        }

        //
        // GET: /ManageDirectors/
        public ActionResult Index()
        {
            var directorsList = repository.GetAll();
            return View(directorsList);
        }

        [HttpGet]
        public ActionResult AddDirector()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddDirector(Director director)
        {
            if (ModelState.IsValid)
            {
                repository.Add(director);
                return RedirectToAction("Index");
            }

            return View(director);
        }

        [HttpGet]
        public ActionResult EditDirector(int directorId)
        {
            var director = repository.GetById(directorId);
            return View(director);
        }

        [HttpPost]
        public ActionResult EditDirector(Director director)
        {
            if (ModelState.IsValid)
            {
                repository.Update(director);
                return RedirectToAction("Index");
            }

            return RedirectToAction("EditDirector", new { directorId = director.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveDirector(int directorId)
        {
            repository.RemoveById(directorId);
            return RedirectToAction("Index");
        }

	}
}

VoD.Website/Views/ManageDirectors/AddDirector.cshtml
@model VoD.Core.Director

@{
    ViewBag.Title = "Dodaj reżysera";
}

<h2>Dodaj reżysera</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reżyser</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

VoD.Website/Views/ManageDirectors/EditDirector.cshtml
@model VoD.Core.Director

@{
    ViewBag.Title = "Edytuj reżysera";
}

<h2>Edytuj reżysera</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reżyser</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

VoD.Website/Views/ManageDirectors/Index.cshtml
@model IEnumerable<VoD.Core.Director>

@{
    ViewBag.Title = "Reżyserzy";
}

<h2>Reżyserzy</h2>

<p>
    @Html.ActionLink("Dodaj nowego", "AddDirector")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "EditDirector", new { directorId=item.Id }) |
            @using (@Html.BeginForm("RemoveDirector", "ManageDirectors", FormMethod.Post, new { @style = "display:inline;" }))
            {
                @Html.AntiForgeryToken()
                <input name="directorId" value="@item.Id" hidden />
                <a class="removePosition">Usuń</a>
            }
        </td>
    </tr>
}

</table>

@section scripts {
    <script src="~/Scripts/helpers.js"></script>
}