VoD.Website/Controllers/ManageGenresController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoD.Core;
using VoD.DAL.Services.Interfaces;
using VoD.Models;

namespace VoD.Website.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ManageGenresController : Controller
    {
        private readonly IGenreRepository repository;

        public ManageGenresController(IGenreRepository repository)
        {
            this.repository = repository;
        }

        //
        // GET: /ManageGenres/
        public ActionResult Index()
        {
            var genresList = repository.GetAll();
            return View(genresList);
        }

        [HttpGet]
        public ActionResult AddGenre()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddGenre(GenreViewModel genreViewModel)
        {
            if (ModelState.IsValid)
            {
                Genre genre = Mapper.Map<GenreViewModel, Genre>(genreViewModel);
                repository.Add(genre);
                return RedirectToAction("Index");
            }

            return View(genreViewModel);
        }

        [HttpGet]
        public ActionResult EditGenre(int genreId)
        {
            var genre = repository.GetById(genreId);
            return View(genre);
        }

        [HttpPost]
        public ActionResult EditGenre(Genre genre)
        {
            if (ModelState.IsValid)
            {
                repository.Update(genre);
                return RedirectToAction("Index");
            }

            return RedirectToAction("EditGenre", new { genreId = genre.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveGenre(int genreId)
        {
            repository.RemoveById(genreId);
            return RedirectToAction("Index");
        }
	}
}

VoD.Website/Views/ManageGenres/AddGenre.cshtml
@model VoD.Models.GenreViewModel

@{
    ViewBag.Title = "Dodaj gatunek";
}

<h2>Dodaj gatunek</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gatunek</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

VoD.Website/Views/ManageGenres/EditGenre.cshtml
@model VoD.Core.Genre

@{
    ViewBag.Title = "Edytuj gatunek";
}

<h2>Edytuj gatunek</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gatunek</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

VoD.Website/Views/ManageGenres/Index.cshtml
@model IEnumerable<VoD.Core.Genre>

@{
    ViewBag.Title = "Gatunki filmowe";
}

<h2>Gatunki filmowe</h2>

<p>
    @Html.ActionLink("Dodaj nowy", "AddGenre")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "EditGenre", new { genreId=item.Id }) |
            @using (@Html.BeginForm("RemoveGenre", "ManageGenres", FormMethod.Post, new { @style = "display:inline;" }))
            {
                @Html.AntiForgeryToken()
                <input name="genreId" value="@item.Id" hidden/>
                <a class="removePosition">Usuń</a>
            }
        </td>
    </tr>
}

</table>

@section scripts {
<script src="~/Scripts/helpers.js"></script>
}